version: '3.4'

services:
  database:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passdb
      POSTGRES_DB: feverdb
    networks:
      - fever-network
  wiremock:
    image: wiremock/wiremock:latest
    command: --port 8090
    ports:
      - "8090:8090"
    volumes:
      - ./src/testFixtures/resources/wiremock/mappings/event/stubs:/./home/wiremock/mappings/
      - ./src/testFixtures/resources/wiremock/mappings/event/response:/./home/wiremock/__files/
    networks:
      - fever-network
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - fever-network
networks:
  fever-network: {}
