spring:
  application:
    name: fever
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/feverdb'
    username: "userdb"
    password: "passdb"
    dbname: "feverdb"
  jpa:
    show-sql: true
  docker:
    compose:
      file: "docker-compose.yml"
      lifecycle-management: "start-and-stop"

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json

app:
  ms-provider-event.url: http://localhost:${wiremock.server.port}
  ms-provider-event.user: guestuser
  ms-provider-event.password: guestuser

wiremock:
  server:
    port: 8090

# swagger http://localhost:8000/swagger-ui/index.html#/

management:
  zipkin:
    tracing:
      endpoint: "zipkin:9411"
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
