spring:
  datasource:
    url: 'jdbc:postgresql://database:5432/feverdb'
    username: "userdb"
    password: "passdb"
    dbname: "feverdb"

app:
  ms-provider-event.url: http://wiremock:8090
  ms-provider-event.user: guestuser
  ms-provider-event.password: guestuser

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411"