DROP TABLE IF EXISTS SHEDLOCK;

CREATE TABLE SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255)
);

ALTER TABLE SHEDLOCK
    ADD CONSTRAINT PK_SHEDLOCK UNIQUE (NAME);

CREATE INDEX IF NOT EXISTS IDX_SHEDLOCK_NAME ON SHEDLOCK (NAME);
